/**
 * @fileoverview gRPC-Web generated client stub for game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: proto/game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.game = require('./game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.AuthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.AuthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.LoginRequest,
 *   !proto.game.LoginResponse>}
 */
const methodDescriptor_AuthService_Login = new grpc.web.MethodDescriptor(
  '/game.AuthService/Login',
  grpc.web.MethodType.UNARY,
  proto.game.LoginRequest,
  proto.game.LoginResponse,
  /**
   * @param {!proto.game.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.game.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.AuthServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.AuthService/Login',
      request,
      metadata || {},
      methodDescriptor_AuthService_Login,
      callback);
};


/**
 * @param {!proto.game.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.game.AuthServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.AuthService/Login',
      request,
      metadata || {},
      methodDescriptor_AuthService_Login);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.ConnectRequest,
 *   !proto.game.GameStateUpdate>}
 */
const methodDescriptor_GameService_Connect = new grpc.web.MethodDescriptor(
  '/game.GameService/Connect',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.game.ConnectRequest,
  proto.game.GameStateUpdate,
  /**
   * @param {!proto.game.ConnectRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.GameStateUpdate.deserializeBinary
);


/**
 * @param {!proto.game.ConnectRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.GameStateUpdate>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.connect =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/Connect',
      request,
      metadata || {},
      methodDescriptor_GameService_Connect);
};


/**
 * @param {!proto.game.ConnectRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.GameStateUpdate>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServicePromiseClient.prototype.connect =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/Connect',
      request,
      metadata || {},
      methodDescriptor_GameService_Connect);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.MoveRequest,
 *   !proto.game.MoveResponse>}
 */
const methodDescriptor_GameService_Move = new grpc.web.MethodDescriptor(
  '/game.GameService/Move',
  grpc.web.MethodType.UNARY,
  proto.game.MoveRequest,
  proto.game.MoveResponse,
  /**
   * @param {!proto.game.MoveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.MoveResponse.deserializeBinary
);


/**
 * @param {!proto.game.MoveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.MoveResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.MoveResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.move =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/Move',
      request,
      metadata || {},
      methodDescriptor_GameService_Move,
      callback);
};


/**
 * @param {!proto.game.MoveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.MoveResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.move =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/Move',
      request,
      metadata || {},
      methodDescriptor_GameService_Move);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.CollectLootRequest,
 *   !proto.game.CollectLootResponse>}
 */
const methodDescriptor_GameService_CollectLoot = new grpc.web.MethodDescriptor(
  '/game.GameService/CollectLoot',
  grpc.web.MethodType.UNARY,
  proto.game.CollectLootRequest,
  proto.game.CollectLootResponse,
  /**
   * @param {!proto.game.CollectLootRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.CollectLootResponse.deserializeBinary
);


/**
 * @param {!proto.game.CollectLootRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.CollectLootResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.CollectLootResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.collectLoot =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/CollectLoot',
      request,
      metadata || {},
      methodDescriptor_GameService_CollectLoot,
      callback);
};


/**
 * @param {!proto.game.CollectLootRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.CollectLootResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.collectLoot =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/CollectLoot',
      request,
      metadata || {},
      methodDescriptor_GameService_CollectLoot);
};


module.exports = proto.game;

